### ISSUE TITLE
Encrypt & Decrypt Tool "index" Not Working

### ISSUE THREAD

**Issue by khavens101** [claudiunderthehood/OfflineRogueEditor#1]
I launched the encrypt & decrypt tool by opening index, and uploaded my data_Guest.prsv file. However nothing happens when I press decrypt. Thanks!

**Comment by claudiunderthehood** [comment]
> I launched the encrypt & decrypt tool by opening index, and uploaded my data_Guest.prsv file. However nothing happens when I press decrypt. Thanks!

Yesterday i deleted the Js script for the html and i didn't notice it, now i've reuploaded it.  #Donload the newest version of this repo and it should work fine!
