### ISSUE TITLE
Is there a way to customize what is printed for data_Guest.json?

### ISSUE THREAD

**Issue by donneeee** [claudiunderthehood/OfflineRogueEditor#2]
Is there a way to modify what get's printed? I'm trying to extract save data and import/raw paste into an excel sheet to auto-populate data for an offline pokedex

dex_data is fine with this:

```1: {
$sa: 149,
$ca: 151,
$na: 136,
$s: 1,
$c: 1,
$hc: 0,
$i: [
23,
11,
19,
27,
13,
15
]
},

2:{
...
```
but as soon as i get to starter_data i'll have some moves in movesets (which i don't want, or have all move sets to be 4 slots of blank spaces as placeholders)

example for pokemon#214, compared to #213.
```
213: {
--
$m: null,
$em: 4,
$x: 5,
$f: 0,
$a: 3,
$pa: 0,
$vr: 0,
$wc: 0
},
214: {
$m: [
33,
350,
292,
31
],
$em: 1,
$x: 0,
$f: 0,
$a: 2,
$pa: 0,
$vr: 1,
$wc: 0
},
215: {
```

i want something like this for something i'm working on in excel/googlesheets
```
213: {
--
$m: [
,  //blank space1
,  //blank space2
,  //blank space3
,  //blank space4
],
$em: 4,
$x: 5,
$f: 0,
$a: 3,
$pa: 0,
$vr: 0,
$wc: 0
},
214: {
$m: [
33,
350,
292,
31
],
$em: 1,
$x: 0,
$f: 0,
$a: 2,
$pa: 0,
$vr: 1,
$wc: 0
},
215: {
```

**Comment by claudiunderthehood** [comment]
Hey there

> Is there a way to modify what get's printed? I'm trying to extract save data and import/raw paste into an excel sheet to auto-populate data for an offline pokedex
> 
> dex_data is fine with this:
> 
> ```
> $sa: 149,
> $ca: 151,
> $na: 136,
> $s: 1,
> $c: 1,
> $hc: 0,
> $i: [
> 23,
> 11,
> 19,
> 27,
> 13,
> 15
> ]
> },
> 
> 2:{
> ...
> ```
> 
> but as soon as i get to starter_data i'll have some moves in movesets (which i don't want, or have all move sets to be 4 slots of blank spaces as placeholders)
> 
> example for pokemon#214, compared to #213.
> 
> ```
> 213: {
> --
> $m: null,
> $em: 4,
> $x: 5,
> $f: 0,
> $a: 3,
> $pa: 0,
> $vr: 0,
> $wc: 0
> },
> 214: {
> $m: [
> 33,
> 350,
> 292,
> 31
> ],
> $em: 1,
> $x: 0,
> $f: 0,
> $a: 2,
> $pa: 0,
> $vr: 1,
> $wc: 0
> },
> 215: {
> ```
> 
> i want something like this for something i'm working on in excel/googlesheets
> 
> ```
> 213: {
> --
> $m: [
> ,  //blank space1
> ,  //blank space2
> ,  //blank space3
> ,  //blank space4
> ],
> $em: 4,
> $x: 5,
> $f: 0,
> $a: 3,
> $pa: 0,
> $vr: 0,
> $wc: 0
> },
> 214: {
> $m: [
> 33,
> 350,
> 292,
> 31
> ],
> $em: 1,
> $x: 0,
> $f: 0,
> $a: 2,
> $pa: 0,
> $vr: 1,
> $wc: 0
> },
> 215: {
> ```

Hey, thanks for reaching out! The tool itself has some standard and built commands for people who just want to cheese out all the json file modification. What you're trying to do is of course doable but not a function that many people would do. For what your problem at hand, If you want to remove all the moves in a Pokemon just put "null" without the "[]". If you want to edit a specific move manually you can use the tool to dump the moves IDs or you can go into the compiled folder, then data, and in there you'll find the json of the moves IDs. I understand that if you're doing this process for all the pokemons you have  it might be a little time consuming, if you want I can implement a function to do that for you but as I said before, not something that many people would use or need. Feel free to inquire more if you need more help!

**Comment by donneeee** [comment]
honestly i'd love that! i'm actually only using the save file decrypter. i am not trying to edit anything and i need/want the data the decrypter prings out to be very specific and unified across all the data it gives me. it'll probably also help in future developement for an ingame pokedex (or anyone trying to do something similar).

but yeah, i am doing this process for ALL pokemon entries and i need to make sure anyone can just copy and paste a json file into a spreadsheet and get correct data shown.

here is what i'm using it for in a nutshell (this is an example):

![image](https://github.com/claudiunderthehood/OfflineRogueEditor/assets/18529235/42c9279b-6d62-4a0f-a41d-67f4c9a2775c)

raw data that i pasted from the decryption:
![image](https://github.com/claudiunderthehood/OfflineRogueEditor/assets/18529235/b22d0734-8157-45d5-aec8-901f3ae2c881)

**Comment by claudiunderthehood** [comment]
> honestly i'd love that! i'm actually only using the save file decrypter. i am not trying to edit anything and i need/want the data the decrypter prints out to be very specific and unified across all the data it gives me. it'll probably also help in future developement for an ingame pokedex (or anyone trying to do something similar).
> 
> but yeah, i am doing this process for ALL pokemon entries and i need to make sure anyone can just copy and paste a json file into a spreadsheet and get correct data shown.
> 
> here is what i'm using it for in a nutshell (this is an example):
> 
> ![image](https://private-user-images.githubusercontent.com/18529235/333802301-42c9279b-6d62-4a0f-a41d-67f4c9a2775c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDQ5NzMsIm5iZiI6MTcxNjY0NDY3MywicGF0aCI6Ii8xODUyOTIzNS8zMzM4MDIzMDEtNDJjOTI3OWItNmQ2Mi00YTBmLWE0MWQtNjdmNGM5YTI3NzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MWQ1N2I3NGRlYzU0ZTNjM2NiZWFlMmYzOTQ1OTM0OWI4YjgwMWVkZjg0ZjgxMmI2MjczMGQxYWIyYWYyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n9kWWENiuuVKjNQ8ARfuG7OuNVGbB6lraVmxFpJ8BDo)
> 
> raw data that i pasted from the decryption: ![image](https://private-user-images.githubusercontent.com/18529235/333802893-a4a7adff-33ed-4d7c-8f17-f3bb07f6599e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDQ5NzMsIm5iZiI6MTcxNjY0NDY3MywicGF0aCI6Ii8xODUyOTIzNS8zMzM4MDI4OTMtYTRhN2FkZmYtMzNlZC00ZDdjLThmMTctZjNiYjA3ZjY1OTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MzlhN2ZjN2JjY2NlMThkNGE3NDI1MzU5NzcwZmI4ZjFiMjI0NzRiYmUzZDcyMjA2MzAzMGRmNzAyNDgyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2LhPefINZhp5PAWfz1YdKEvoIFlz7S5NLv_4banGZy4)

That sounds like a huge work, especially because you have to do some data scraping and select only the data you want for the Pokédex, like the number, forms, shiny forms ecc. Currently I'm working on a fix for the Editor of the Online version which is a little tricky but when I'll have 5 minutes I'll implement a command that clears you the moves of all pokemons.

**Comment by donneeee** [comment]
that'd be great! thanks

**Comment by donneeee** [comment]
before i forget to ask, could that script be an option in the encrypt/decrypt tool? 

![image](https://github.com/claudiunderthehood/OfflineRogueEditor/assets/18529235/fc467d49-ff0f-4ea9-900b-88ed1400b067)

maybe as not an option but checkbox before decryption?

my intention is for someone to just copy and paste a correct json with the least amount of steps/programs/apps involved.

**Comment by claudiunderthehood** [comment]
> before i forget to ask, could that script be an option in the encrypt/decrypt tool?
> 
> ![image](https://private-user-images.githubusercontent.com/18529235/333805908-7b553424-a312-4be9-a451-6a746ba465e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDY2OTksIm5iZiI6MTcxNjY0NjM5OSwicGF0aCI6Ii8xODUyOTIzNS8zMzM4MDU5MDgtN2I1NTM0MjQtYTMxMi00YmU5LWE0NTEtNmE3NDZiYTQ2NWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE0MTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNGUzODc4ODVlNDMxYjE0MjRlZjdmYjlmOTY0ZTkwNGMzOTc0MzVhMGRmNGE0ZWIzMDg5NDdlYTBhNDNkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gLVOkaNtSONBJCeYZTQyO53PwQWtWzGcLpyRyo-pKM4)
> 
> my intention is for someone to just copy and paste a correct json with the least amount of steps/programs/apps involved.

I've just committed what you were asking, sorry if the HTML isn't clean but front end and graphics aren't my forte. When decrypting the prsv file, before pressing the decrypt button, check the remove starters moveset and then press decrypt as usual and it should work!

**Comment by donneeee** [comment]
Testing it now! and it's no problem on the HTML! so long as everything is in one place for me

**Comment by donneeee** [comment]
you are amazing and a saint! looks like it worked, i can finally move onto final phase of my project xD

**Comment by claudiunderthehood** [comment]
> Testing it now! and it's no problem on the HTML! so long as everything is in one place for me

Yeah I've always been terrible with this stuff sorry. The reason the encrypt&decrypt tool is in JS is because I'm using the same library they used and it is pretty straightforward while in python I wasn't able to make good encryptions/decryptions.

**Comment by claudiunderthehood** [comment]
> you are amazing and a saint! looks like it worked, i can finally move onto final phase of my project xD

No worries, hmu if you need anything 

discord: claudiunderthehood

**Comment by donneeee** [comment]
it's all good on that end. this is the only tool i found so far that is super easy for anyone to use. the rest of the tools i found all involve using credentials and/or external programs; all of which i did not want. 

i'll hit you up if i need anything else for sure!
