### ISSUE TITLE
Import Data

### ISSUE THREAD

**Issue by Oloxos** [claudiunderthehood/OfflineRogueEditor#3]
I followed the steps using the editor offline, but at the end, i can't find the import data. I don't know if it is a online problem, with all the ddos attack or else. The import data and import session button does not appear on my game. (I'm using Admiral-billy's version of pokerogue)

**Comment by claudiunderthehood** [comment]
> I followed the steps using the editor offline, but at the end, i can't find the import data. I don't know if it is a online problem, with all the ddos attack or else. The import data and import session button does not appear on my game. (I'm using Admiral-billy's version of pokerogue)

Hey. After the DDOS attacks ALL the online versions of this game have been slightly changed. This tool only works for the offline versions, even for the admiral-billy's version this tool only works for the offline version of it!

**Comment by Oloxos** [comment]
I did it, thanks for taking the time to answer me ! :D

**Comment by claudiunderthehood** [comment]
> I did it, thanks for taking the time to answer me ! :D

No problem! Feel free to ask if you've further issues!
