### ISSUE TITLE
Bug: Need attention immediately

### ISSUE THREAD

**Issue by JulianStiebler** [claudiunderthehood/OfflineRogueEditor#32]
Cant really describe it as its not my bug-report but it got issued to me.

"k so 9 10 11 -> exception
3 4 5 7 nothing
1 6 8 closing "

![grafik](https://github.com/claudiunderthehood/OfflineRogueEditor/assets/68881884/f4c67026-9851-428c-b157-ff0b259ddff9)

Works fine on my computer tho.
Can you test the windows executable @claudiunderthehood aswell?

**Comment by claudiunderthehood** [comment]
> Cant really describe it as its not my bug-report but it got issued to me.
> 
> "k so 9 10 11 -> exception 3 4 5 7 nothing 1 6 8 closing "
> 
> ![grafik](https://private-user-images.githubusercontent.com/68881884/334272653-f4c67026-9851-428c-b157-ff0b259ddff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODMyNjUsIm5iZiI6MTcxNjg4Mjk2NSwicGF0aCI6Ii82ODg4MTg4NC8zMzQyNzI2NTMtZjRjNjcwMjYtOTg1MS00MjhjLWIxNTctZmYwYjI1OWRkZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA3NTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMGEyYzU0ODM5Y2Q1YjZkMTBmMDM0ZTAzZTYzYWM1NDE3YmVkZWY4ZjNjZjIyMTc2ZGM2MWE0ZjdmNjA2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sdCYPR78hMxqH-jfF3BpgCdZPETqlOnDwD86oFH1Ma8)
> 
> Works fine on my computer tho. Can you test the windows executable @claudiunderthehood aswell?

Tested and every functions that was giving troubles works fine for me too:

![b1](https://github.com/claudiunderthehood/OfflineRogueEditor/assets/33903941/20cd8800-34cb-4be1-ae31-6927f3d32970)

Possibly the json file they're trying to use is invalid or not formatted.

**Comment by claudiunderthehood** [comment]
> > Cant really describe it as its not my bug-report but it got issued to me.
> > "k so 9 10 11 -> exception 3 4 5 7 nothing 1 6 8 closing "
> > ![grafik](https://private-user-images.githubusercontent.com/68881884/334272653-f4c67026-9851-428c-b157-ff0b259ddff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODMyNjUsIm5iZiI6MTcxNjg4Mjk2NSwicGF0aCI6Ii82ODg4MTg4NC8zMzQyNzI2NTMtZjRjNjcwMjYtOTg1MS00MjhjLWIxNTctZmYwYjI1OWRkZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA3NTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMGEyYzU0ODM5Y2Q1YjZkMTBmMDM0ZTAzZTYzYWM1NDE3YmVkZWY4ZjNjZjIyMTc2ZGM2MWE0ZjdmNjA2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sdCYPR78hMxqH-jfF3BpgCdZPETqlOnDwD86oFH1Ma8)
> > Works fine on my computer tho. Can you test the windows executable @claudiunderthehood aswell?
> 
> Tested and every functions that was giving troubles works fine for me too:
> 
> ![b1](https://private-user-images.githubusercontent.com/33903941/334318706-20cd8800-34cb-4be1-ae31-6927f3d32970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODM1MjksIm5iZiI6MTcxNjg4MzIyOSwicGF0aCI6Ii8zMzkwMzk0MS8zMzQzMTg3MDYtMjBjZDg4MDAtMzRjYi00YmUxLWFlMzEtNjkyN2YzZDMyOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA4MDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMjZmOWY1Nzk2YWE5MTRlNTY4Y2I2NGE5OGFiNzk5YWVkZGIwY2MyNzc2YTMyZjgyMWEyMjBiZTk5ZjI5N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Srf1aLlQx4wuRB6SRXhFWbBWrfNijpooptLzsyrBSE4)
> 
> Possibly the json file they're trying to use is invalid or not formatted.

or perhaps the editor doesn't have enough permissions.

**Comment by JulianStiebler** [comment]
Either or i suppose, If they work both on us we can't really do much anyway. He didnt gave clearer Instructions either but i figured still to mention it.
