### ISSUE TITLE
What happened to the Online Version?

### ISSUE THREAD

**Issue by RipVanWinkle397** [claudiunderthehood/OfflineRogueEditor#9]
I know you and a few others were working on the online? It comes up as a 404. Did Fire6945 quit? Will you be working on a new online version?

**Comment by claudiunderthehood** [comment]
> I know you and a few others were working on the online? It comes up as a 404. Did Fire6945 quit? Will you be working on a new online version?

Hey, yeah the repo has disappeared out of nowhere and the owner didn't even speak to me about it. Luckily I had all the work done for the new version in another repo so yeah I'll keep working on it and when it'll be done I'll publish it in here. You can add me on discord, the username is the same that I have in here. Sorry for the complication.

**Comment by JulianStiebler** [comment]
Since i have my main-account now back i also like to offer help in figuring things out. Added you on discord (im also prephalia from comments in the main-editor repo)

**Comment by RipVanWinkle397** [comment]
Cool beans mate. Your work is greatly appreciated.

**Comment by Valsahn** [comment]
True goat of the game !

**Comment by JulianStiebler** [comment]
Closing!
